name: PR Merged

on:
  pull_request:
    types: [ closed ]

jobs:
  start:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx pnpm i
      - name: 'Update README index'
        run: npm run readme
      - uses: EndBug/add-and-commit@v9
        with:
          branch: master
          message: 'chore: update index'
